on:
  post:
    - kind: regexp
      file: deno.jsonc
      pattern: '(?<="version": ").*(?=",)'
    - kind: regexp
      file: README.md
      pattern: '(?<=/gh-triage/).*(?=/.*)'
    - kind: regexp
      file: install.sh
      pattern: '(?<=/gh-triage/).*(?=/.*)'
      flags: g
